"""
loss.py — Feature Alignment Loss (L_feat)

This module implements the cross-modal alignment loss used during Stage 2
training of the Blind-VLA framework. The objective is to align the predicted 
tactile embeddings (z_V_hat), generated by the projection head f_theta, with the 
ground-truth visual latent space (z_V) derived from a frozen OpenVLA vision encoder.

The loss function consists of two complementary components:
  1. Mean Squared Error (MSE): Aligns the structural magnitude and statistical 
     scale of the representations.
  2. Cosine Dissimilarity: Aligns the directional orientation within the high-
     dimensional latent space.

Mathematical Formulation:
    L_feat = MSE(z_V_hat, z_V) + lambda_cos * (1 - CosineSimilarity(z_V_hat, z_V))
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class FeatureAlignmentLoss(nn.Module):
    """
    Computes the composite objective function L_feat for cross-modal alignment.
    
    The multi-objective formulation guarantees that the projected tactile 
    embeddings preserve both the absolute magnitude (via MSE) and the angular 
    direction (via Cosine Similarity) required by the downstream frozen 
    Vision-Language-Action (VLA) policy.
    """

    def __init__(self, lambda_cos: float = 1.0, reduction: str = "mean"):
        """
        Args:
            lambda_cos (float): Scaling factor to balance the cosine dissimilarity 
                component against the magnitude-based MSE loss. Default: 1.0.
            reduction (str): Specifies the reduction to apply to the output:
                'none' | 'mean' | 'sum'. Default: 'mean'.
        """
        super().__init__()
        self.lambda_cos = lambda_cos
        self.reduction  = reduction
        self.mse        = nn.MSELoss(reduction=reduction)

    def forward(
        self,
        z_V_hat: torch.Tensor,   # Shape: (B, D_VISUAL) -> Projected tactile embeddings
        z_V:     torch.Tensor,   # Shape: (B, D_VISUAL) -> Ground-truth visual embeddings (cached)
    ) -> tuple[torch.Tensor, dict]:
        """
        Executes the forward pass for the alignment loss computation.

        Args:
            z_V_hat (torch.Tensor): Predicted visual latents from f_theta.
            z_V (torch.Tensor): Target visual features extracted from nominal frames.

        Returns:
            tuple:
                - loss (torch.Tensor): Scalar tensor representing the total loss.
                - info (dict): Diagnostic dictionary containing itemized loss 
                  components and metrics for logging and monitoring.
        """

        # ── Component 1: Mean Squared Error (MSE) ────────────────────────
        # Measures the average squared Euclidean distance between the predicted
        # and target vectors, enforcing scale consistency.
        loss_mse = self.mse(z_V_hat, z_V)

        # ── Component 2: Cosine Dissimilarity ────────────────────────────
        # Computes 1 - CosineSimilarity to map a perfect directional alignment 
        # (cosine = 1.0) to an optimal loss value of 0.0.
        cos_sim  = F.cosine_similarity(z_V_hat, z_V, dim=-1)  # Shape: (B,)
        loss_cos = (1.0 - cos_sim)

        if self.reduction == "mean":
            loss_cos = loss_cos.mean()
        else:
            loss_cos = loss_cos.sum()

        # ── Total Composite Loss ─────────────────────────────────────────
        loss = loss_mse + self.lambda_cos * loss_cos

        # Populate telemetry dictionary for experiment tracking (e.g., WandB/TensorBoard)
        info = {
            "loss_total":  loss.item(),
            "loss_mse":    loss_mse.item(),
            "loss_cosine": loss_cos.item(),
            "cos_sim_mean": cos_sim.mean().item(),
        }

        return loss, info


# ─────────────────────────────────────────────────────────────
#  Validation & Evaluation Metrics
# ─────────────────────────────────────────────────────────────

@torch.no_grad()
def compute_alignment_metrics(
    z_V_hat: torch.Tensor,
    z_V:     torch.Tensor,
) -> dict:
    """
    Computes deterministic cross-modal alignment metrics for model validation.
    This function runs without tracking gradients.

    Metrics computed:
      - cosine_similarity_mean : Average angular alignment across the batch (Target: > 0.8).
      - cosine_similarity_std  : Standard deviation of angular alignment (indicates uniformity).
      - mse                    : Mean Squared Error across all features.
      - relative_norm_error    : Mean absolute relative difference in norm magnitude 
                                 (||z_V_hat|| - ||z_V||) / ||z_V||.

    Returns:
        dict: A dictionary mapping metric names to their scalar float values.
    """
    cos_sim = F.cosine_similarity(z_V_hat, z_V, dim=-1)   # Shape: (B,)
    mse     = F.mse_loss(z_V_hat, z_V)

    norm_hat = z_V_hat.norm(dim=-1)   # Shape: (B,)
    norm_ref = z_V.norm(dim=-1)       # Shape: (B,)
    rel_norm = ((norm_hat - norm_ref).abs() / norm_ref.clamp(min=1e-8)).mean()

    return {
        "cosine_similarity_mean":  cos_sim.mean().item(),
        "cosine_similarity_std":   cos_sim.std().item(),
        "mse":                     mse.item(),
        "relative_norm_error":     rel_norm.item(),
    }